version: '3.8'

services:
  web:
    build: .
    container_name: inventario-web
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/app/instance
      - ./static:/app/static
      - ./backups:/app/backups
      - ./reports:/app/reports
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - red-inventario

  programador:
    build: .
    container_name: inventario-programador
    restart: always
    command: python scheduler.py
    volumes:
      - ./instance:/app/instance
      - ./static:/app/static
      - ./backups:/app/backups
      - ./reports:/app/reports
    env_file:
      - .env
    depends_on:
      - web
    networks:
      - red-inventario

  nginx:
    image: nginx:alpine
    container_name: inventario-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/app/static:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - web
    networks:
      - red-inventario

volumes:
  instance:
  static:
  backups:
  reports:

networks:
  red-inventario:
    driver: bridge
